version: '2'

services:
  web:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - './docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro'
      - '.:/usr/src/app'
    depends_on:
      - php

  php:
    image: desmart/php:7.1-fpm-debian
    volumes:
      - '.:/usr/src/app'